### PR TITLE
extends the README with Matt Stibbs's nhsnumber.info content

### PR DESCRIPTION
**Pull request by pacharanero**
I have pulled in the content from @mattstibbs [Matt Stibbs' nhsnumber.info pages](https://github.com/mattstibbs/nhsnumber.info) and added them to the README.md

Also added some basic Installation and Usage info (pending checking/verification that it works as indicated) and a list of the current Authors/Contributors - at this stage really all the code in the repo is written by @andylaw but eventually all contributors will all have at least reviewed the code for errors, added improvements etc.

### CODE REVIEW

**Comment by andylaw** [comment]
@pacharanero - why is the Scotland range split into two entries in the table? Is there some functional or historical significance to that? Also, is there some reference source to define the separation and reservation of range for Ireland?

**Comment by pacharanero** [comment]
@andylaw I don't have a reference for the Republic of Ireland usage but I could do some further digging, it would be interesting to be able to report where a number is from, accurately.

Some information is from the Wikipedia article https://en.wikipedia.org/wiki/NHS_number and referenced, however I would have to defer to @mattstibbs for any more detail.

**Comment by eatyourpeas** [comment]
https://www.datadictionary.nhs.uk/attributes/health_and_care_number.html

From: Marcus Baw ***@***.***>
Date: Tuesday, 23 May 2023 at 13:46
To: uk-fci/nhs-number ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [uk-fci/nhs-number] extends the README with Matt Stibbs's nhsnumber.info content (PR #3)

@andylaw<https://github.com/andylaw> I don't have a reference for the Republic of Ireland usage but I could do some further digging, it would be interesting to be able to report where a number is from, accurately.

Some information is from the Wikipedia article https://en.wikipedia.org/wiki/NHS_number and referenced, however I would have to defer to @mattstibbs<https://github.com/mattstibbs> for any more detail.

**Comment by andylaw** [comment]
@eatyourpeas - that reference describes the Northern Ireland block. I'm still not seeing any evidence that the Republic of Ireland has a block of numbers reserved in the UK NHS Number system.

@pacharanero - the Scottish block is one single block and should be represented as such in the table

@pacharanero - the number '1234567890' is not a valid NHS number and the call to `is_valid()` should return False

@pacharanero - there is no `normalise()` signature in the `nhs-number` package, plus the `normalise_number()` function does the _opposite_ of what your example `normalise()` call does i.e. it removes spaces and hyphens leaving just a string of digits to process

**Comment by eatyourpeas** [comment]
Just adding [this](https://www.hse.ie/eng/about/who/national-services/individual-health-identifier/questions-regarding-the-individual-health-identifier-ihi-number.pdf) - It is likely others no more than me, but I am not sure RoI is within scope because the HSE is not really the same as the NHS, and while they have an IHI number, it is not an NHS number.

**Comment by andylaw** [comment]
I propose that the Republic of Ireland be considered **out of scope**

**Comment by pacharanero** [comment]
I agree that for now the Republic of Ireland be descoped for this package as it has no immediate relevance. I know people who work at the HSE on the IHI project and I did a bit of research yesterday into what exactly is used for the IHI in Ireland. If it turns out that they are using exactly the same validation technique as the NHS Number then it makes sense we would document that in this library. For now assume ROI descoped but I will bring this back if it makes sense to.

**Comment by pacharanero** [comment]
I found some corroborative evidence to support the assertion that a range of NHS Numbers **was** indeed reserved for ROI: https://digital.nhs.uk/about-nhs-digital/contact-us/freedom-of-information/freedom-of-information-disclosure-log/december-2022/nic-690159-k8h4z

I have contacted my HSE friend who will let me know exactly what validation algorithm and number range is being used by IHI.

I've fixed the issues with the README that were pointed out here: 

> @pacharanero - the number '1234567890' is not a valid NHS number and the call to `is_valid()` should return False
> 
> @pacharanero - there is no `normalise()` signature in the `nhs-number` package, plus the `normalise_number()` function does the _opposite_ of what your example `normalise()` call does i.e. it removes spaces and hyphens leaving just a string of digits to process

**Review by eatyourpeas — APPROVED** [review]
thanks m nice work

**Pull request merged**
